### ISSUE TITLE
Runtime error on module.exports

### ISSUE THREAD

**Issue by JonSilver** [simbathesailor/use-what-changed#1]
`TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

This error occurs in `node_modules/@simbathesailor/use-what-changed/dist/use-what-changed.esm.js:119` which is a product of the Typescript transpilation process.

The errant line is `module.exports = useWhatChanged;` which cannot be used with `import`.

The original line of code is `export { useWhatChanged };`

I think something's gone wrong with the transpilation process. Wrong target?

**Comment by simbathesailor** [comment]
Ahh I think We cant mix import and module.exports. https://github.com/webpack/webpack/issues/4039#issuecomment-273804003
I have published a new version of this package. Now import changes to : 

`
import useWhatChanged from "@simbathesailor/use-what-changed"
`

`
import { useWhatChanged } from "@simbathesailor/use-what-changed"
`

**Comment by JonSilver** [comment]
Yup, that works :)
