### ISSUE TITLE
Allow renaming useEffect to useWhatChanged, and adding 3rd arg for dependencies label

### ISSUE THREAD

**Issue by devinrhode2** [simbathesailor/use-what-changed#15]
I was editing [my stackoverflow answer](https://stackoverflow.com/questions/55187563/determine-which-dependency-array-variable-caused-useeffect-hook-to-fire/63837778?noredirect=1#comment112899058_63837778) pointing to this project, and realized there could be a much better api when you are not using the babel plugin

My idea is to allow developers to change this code:
```
useEffect(() => {
  console.log(bar)
}, [bar]);
```
to this:
```
useWhatChanged(() => {
  console.log(bar)
}, [bar], 'bar');
```

Please ignore this comment/imagine I removed it in an edit/deleted it:
> When I was using useWhatChanged, I noticed once I remove the "bad" deps from my useEffect hook, things were still re-rendering, until I removed them from useWhatChanged

**Comment by simbathesailor** [comment]
Thanks @devinrhode2  for the feedback. Could you please share me a codesanbox link. Here (https://codesandbox.io/s/simabthesailoruse-what-changed-demo-q94rn)is the one, from which you can fork it and add your use-case. That will help to understand it better

**Comment by devinrhode2** [comment]
I'm suggesting that useWhatChanged can/could act as a simple wrapper around useEffect.
So useWhatChanged might be like this:
```
import {useEffect} from 'react';

export const useWhatChanged = (normalUseEffectUserCallback, deps, depLabels) => {
  useEffect(normalUseEffectUserCallack, deps);
  _internal_current_useWhatChanged(deps, depLabels);
};
```

Of course `_internal_current_useWhatChanged` is just pseudo code/placement holder for the real code.

**Comment by devinrhode2** [comment]
Actually, this idea could be implemented in user-land, outside your package source, like so:
```
import {useEffect} from 'react';
import { useWhatChanged as core_useWhatChanged } from '@simbathesailor/use-what-changed';

const useWhatChanged = (normalUseEffectUserCallback, deps, depLabels) => {
  useEffect(normalUseEffectUserCallack, deps);
  core_useWhatChanged(deps, depLabels);
};

// inside react component:
useWhatChanged(() => {
  console.log(bar)
}, [bar], 'bar');
```

**Comment by simbathesailor** [comment]
This is really cool @devinrhode2 
I think , I need to add a support for switching of the logging in an application via one time configuration(similar to how we configure apollo and axios in one file). That way , people not using babel plugin can switch off logging at one place. and then they can make use of your approach. 
If you are interested , you can give it a shot , or I will do it in few days.
Thanks

**Comment by simbathesailor** [comment]
I have added the support to enable/disable logging via one time call or based on NODE_ENV key now. Although I have supported this configuration, I must recommend to use [https://github.com/simbathesailor/babel-plugin-use-what-changed](https://github.com/simbathesailor/babel-plugin-use-what-changed) for better dev experience. Closing the ticket  for now.
